.editorconfig, .travis.yml, Dockerfile, README.md, build.gradle, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/util/HtmlFieldFormatter.java, src/main/resources/data/templates/divorceminipetition.html, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/util/HtmlFieldFormatterUTest.java
Support for special characters in the Mini Petition and additional changes to Mini Petition
Tested using the automated test
* Hardware:
* JDK:
=> Sync local repo changes to GitHub

build.gradle
Increased the version of the `div-document-generator-client` to 2.2.0
=> Increase the version to 2.2.0

build.gradle, dependency-check-suppressions.xml
=> OWASP dependency check

src/integrationTest/resources/documentgenerator/d8minipetition/jsoninput/CC--cores_FO--ChildApp_CN--BCDE_DR-AD-CRK-Yes-PL-Yes-DT-Yes_LP--Yes-Petitioner-Solicitor.json, src/main/resources/data/templates/divorceminipetition.html
=> Remove derived from minipetition

infrastructure/main.tf
=> [PREVIEW] cnp_vault remove key-vault module

Jenkinsfile_nightly, README.md, build.gradle, dependency-check-suppressions.xml, src/integrationTest/java/uk/gov/hmcts/reform/divorce/IntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/ServiceContextConfiguration.java, src/kubernetes/deployment.template.yaml
=> Enable mutation nightly

src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/functionaltest/DocumentGenerateAndStoreE2ETest.java
Noticed that our unit test PowerMockRunners and and MockitoRunners do not seem to add to coverage. Only the functional test using SpringRunner seems to add to the coverage, so I added two more tests here.
=> Added functional tests for switch filename case

src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/config/HttpConnectionConfiguration.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/management/monitoring/health/EvidenceManagementClientHealthCheck.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/management/monitoring/health/PDFServiceHealthCheck.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/management/monitoring/health/ServiceAuthProviderHealthCheck.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/management/monitoring/health/HealthCheckITest.java
To ensure /health responds in a reasonable time
Fixes #DIV-3885
Automated tests
=> DIV-3885 - set a separate timeout for health checks

Jenkinsfile_nightly, security.sh
=> set up divorce dgs security scan

src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/functionaltest/DocumentGenerateAndStoreE2ETest.java
Added functional test 
* Hardware:
* JDK:
=> Added functional test

src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/controller/DocumentGeneratorController.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/DocumentManagementServiceImpl.java, src/main/resources/data/templates/aosinvitation.html, src/main/resources/data/templates/co-respondentinvitation.html
Changing font style for the access code in respondent and co-respondent invitation letters.
Manually
=> DIV-4406: Applied new styling to access code

src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/DocmosisPDFGenerationServiceImplUTest.java
A broken test on pipeline, this fixes it.
=> Fix broken test

infrastructure/prod.tfvars
Adds the docmosis url for Production.
=> Add Production Docmosis Url for Prod Env

src/integrationTest/resources/documentgenerator/documents/jsoninput/Resp_2Year_Solicitor_Defend_Response.json, src/main/resources/data/templates/respondentAnswers.html
https://tools.hmcts.net/jira/browse/DIV-4901
=> Field name change

src/integrationTest/java/uk/gov/hmcts/reform/divorce/EMStoreIntegrationTest.java, src/integrationTest/resources/documentgenerator/dn.json, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/domain/TemplateConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/DocumentManagementServiceImpl.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/functionaltest/DocumentGenerateAndStoreE2ETest.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapperTest.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/DocumentManagementServiceImplUTest.java
[DIV-4829 Decree Nisi Document](https://tools.hmcts.net/jira/browse/DIV-4829)
This PR allows DGS to generate the Decree Nisi document in Docmosis on request.
Automated Testing
=> Decree Nisi Document Generation

src/main/resources/data/templates/divorcedraftminipetition.html
https://tools.hmcts.net/jira/browse/DIV-4976?focusedCommentId=597761&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-597761
* Hardware:
* JDK:
=> DIV-4977: place of marriage may be blank when draft of mini petition is generated

src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/domain/TemplateConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/factory/PDFGenerationFactory.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/DocumentManagementServiceImpl.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/functionaltest/DocumentGenerateAndStoreE2ETest.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/DocumentManagementServiceImplUTest.java
Including the Docmosis template information for the list with cases to be pronounced.
Unit tests and manually by using CCD.
=> DIV-4826: Adding new template id

infrastructure/variables.tf, src/integrationTest/java/uk/gov/hmcts/reform/divorce/IntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/PDFGenerationTest.java, src/integrationTest/resources/application.properties, src/integrationTest/resources/example-application-local.properties, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/DocumentManagementServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/functionaltest/DocumentGenerateAndStoreE2ETest.java
Feature toggle set to true is not picked in the integration tests
=> Feature toggle fix in integration tests and making toggle to string

infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
=> [PREVIEW] Made docmosis vault name variable confgurable by env

infrastructure/prod.tfvars
=> Make docmosis vault a string value

src/integrationTest/resources/documentgenerator/da.json, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/domain/TemplateConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapperTest.java
DecreeAbsoluteGrantedDate has been changed from CCD Date Type to CCD DateTime Type as per Product Owner requirements. This PR is therefore needed to update the Mapping so it can display correctly on the generated Document.
* Hardware:
* JDK:
=> Map DecreeAbsoluteGrantedDate from DateTime format

charts/div-dgs/values.aat.template.yaml, charts/div-dgs/values.preview.template.yaml, infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/preview.tfvars, infrastructure/variables.tf, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/domain/request/PdfDocumentRequest.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/DocmosisPDFGenerationServiceImpl.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/DocmosisPDFGenerationServiceImplUTest.java
[DIV-5257](https://tools.hmcts.net/jira/browse/DIV-5257)
This will prevent failing Docmosis templates from breaking the build on AAT.
* Hardware:
* JDK:
=> Add flag for DevMode to Docmosis

src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/domain/TemplateConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapperTest.java
https://tools.hmcts.net/jira/browse/DIV-4854
=> Behaviour/Adultery  date formatting for docmosis template

Jenkinsfile_CNP, charts/div-dgs/values.aat.template.yaml, charts/div-dgs/values.preview.template.yaml, src/integrationTest/resources/documentgenerator/documents/jsoninput/AOS_Offline-Invitation-Letter-Co-Respondent.json, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/controller/DocumentGenerateDownloadController.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/controller/DocumentGeneratorController.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/controller/DocumentGenerateDownloadControllerTest.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/controller/DocumentGeneratorControllerUTest.java
* Hide unused endpoint under test flag (only enabled for in PRs) - this was causing an issue in the nightly pipeline because the ZAP test detected it as insecure 
* Fixed incorrect test data for functional test
Fixes pipeline
=> Fix security error/test on master and nightly pipelines

Jenkinsfile_CNP
This was added by mistake while trying to test a zap security issue in #185 
=> Removed security scan

web.config
Missed this in #191 
Fixes pipeline
=> Fixed webconfig appinsights version

Jenkinsfile_CNP, charts/div-dgs/values.aat.template.yaml, charts/div-dgs/values.preview.template.yaml
* Removed unused config values
* Added `enableAksStagingDeployment` step to Jenkinsfile
* added `aadIdentityName` value as required
Similar to the work done in https://github.com/hmcts/div-evidence-management-client-api/commit/d468b043e339ce28561eccfc21a97b96b075e165
Linked to https://github.com/hmcts/cnp-flux-config/pull/491
Fixes #DIV-5518
=> DIV-5517 - enable AKS AAT deployment

infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/saat.tfvars, infrastructure/sandbox.tfvars, infrastructure/sprod.tfvars
=> cleanup ASEs

infrastructure/variables.tf
Most tf files were removed in #207 so a default for this is needed
Fixes #DIV-5839
=> DIV-5839 - added missing vault_env

README.md
Dummy update to generate a new container
* Hardware:
* JDK:
=> Dummy update

src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/DocumentManagementServiceImpl.java
=> Add case id log

build.gradle, security.sh
applied fixes suggested on 
https://tools.hmcts.net/confluence/display/RQA/Integrate+with+Glue+for+ignoring+false+postivies
=> fix zap python compatibility issue

build.gradle, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/domain/TemplateConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapperTest.java
New parameters added for Welsh Translation For PDF Letter : AOS INVITATION
WLA-303
- [ x] New feature (non-breaking change which adds functionality)
Unit tested 
* Hardware:
* JDK:
=> Wla 303 aos invitation

src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/config/LanguagePreference.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/config/TemplateConfig.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/domain/TemplateConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/util/LocalDateToWelshStringConverter.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapperTest.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/util/LocalDateToWelshStringConverterTest.java
Welsh parameter keys for bilingual template
WLA-306
- [ X] New feature (non-breaking change which adds functionality)
Unit tested
* Hardware:
* JDK:
=> WLA-306:Divorce Draft Mini Petition

src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/domain/TemplateConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapperTest.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/util/LocalDateToWelshStringConverterTest.java
New Welsh parameters for divorce mini petiion 
https://tools.hmcts.net/jira/browse/WLA-307
Unit and integration tested
* Hardware:
* JDK:
=> WLA-307:Divorce Mini Petition

src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/domain/TemplateConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/DocumentManagementServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapperTest.java
Added new featureToggleRespSolicitor key to the template parameters
https://tools.hmcts.net/jira/browse/WLA-303
Bilingual 
* Hardware:
* JDK:
=> WLA-303:Welsh AOS invitation

src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/domain/TemplateConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapperTest.java
Welsh Translation For PDF Letter : Co-Respondent Invitation
https://tools.hmcts.net/jira/browse/WLA-305
- [ X] New feature (non-breaking change which adds functionality)
Unit tested
* Hardware:
* JDK:
=> WLA-305: Welsh Translation For PDF Letter : Co-Respondent Invitation

src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/domain/TemplateConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/WelshTemplateDataMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/WelshTemplateDataMapperTest.java
WLA-523 Decree Nisi Granted Bilingual issues
* Hardware:
* JDK:
=> WLA-523: Decree Nisi Granted Bilingual issues

src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/WelshTemplateDataMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/util/LocalDateToWelshStringConverter.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/WelshTemplateDataMapperTest.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/util/LocalDateToWelshStringConverterTest.java
Grant Issue date conversion error
* Hardware:
* JDK:
=> WLA-567 Decree Absolute Grant throwing an exception

src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/domain/TemplateConstants.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapperTest.java
Updating court contact address on decree nisi certificate
[RPET-312](https://tools.hmcts.net/jira/browse/RPET-312)
Added tests.
* Hardware:
* JDK:
=> RPET-312 Change court contact address for decree nisi

src/integrationTest/resources/documentgenerator/documents/jsoninput/cost-order-cover-letter-co-respondent.json, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/domain/TemplateConstants.java, src/main/resources/application.yml
Template renamed:
https://github.com/hmcts/rdo-docmosis/pull/327
=> using renamed template: FL-DIV-LET-ENG-00358 -> FL-DIV-LET-ENG-00358A

src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/DocumentManagementServiceImplUTest.java
Sonar passing score may be more stricter on Master branch, PR is to satisfy an existing warning
https://tools.hmcts.net/jira/browse/DIV-6140
=> DIV-6140-Sonar fix

build.gradle, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/EvidenceManagementServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/EvidenceManagementServiceImplUTest.java
https://tools.hmcts.net/jira/browse/DIV-6140
Sonar fix to master, updating small fragments of code.
=> DIV-6140-Sonar warning update

Dockerfile, README.md, build.gradle, lombok.config, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/DocmosisPDFGenerationServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/EvidenceManagementServiceImplUTest.java
Upgrade Java to 11.
https://tools.hmcts.net/jira/browse/RPET-263
=> RPET 263: Upgrade java 11

Jenkinsfile_CNP, build.gradle, dependency-check-suppressions.xml, src/contractTest/java/uk/gov/hmcts/reform/divorce/documentgenerator/PDFDGenerationServiceConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/divorce/documentgenerator/PdfGGenerationServiceConsumerTest.java, src/contractTest/resources/application.yml
=> TA-32: Initial cut of Consumer Test code for PDF service

build.gradle
Using a safe version of junit.
=> Fixing dependency vulnerability issue

build.gradle
Fixing new dependency vulnerability
Existing tests.
=> DIV-6689: Fixing new dependency vulnerability

build.gradle
=> Fixing vulnerabilities

build.gradle
Having a look at the build to fix issue with master.
=> DGS build issue Investigation

dependency-check-suppressions.xml
=> Cleanup suppressions file

charts/div-dgs/Chart.yaml, charts/div-dgs/values.yaml, src/main/resources/bootstrap.yaml
=> fix logs not showing up in Azure

src/integrationTest/java/uk/gov/hmcts/reform/divorce/IdamUtils.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/model/CreateUserRequest.java, src/integrationTest/resources/example-application-local.properties
We no longer use the proxy locally and user group only slows the user creation process.
Manual test
=> Making some changes to integration test

charts/div-dgs/Chart.yaml
Upgrading to latest version of [chart-java (3.4.5)](https://github.com/hmcts/chart-java/releases/tag/v3.4.5)
https://tools.hmcts.net/jira/browse/RPET-921
platform operations upgrade
=> RPET-921 chart java bump

src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/util/ResourceLoader.java
Always close resource
Always close resource
https://tools.hmcts.net/jira/browse/DFR-101
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] New and existing unit tests pass locally with my changes
=> DFR-101 : Always close resource

Jenkinsfile_nightly, build.gradle, config/fortify-client.properties
Feature # (issue)
DFR-465
fortify integration
On nightly pipeline
=> DFR-465: fortify integration

build.gradle
=> DFR-714: upgrade log4j

build.gradle
=> DFR-728: upgrade log4j 2.16.0

src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/util/LocalDateToWelshStringConverter.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapperTest.java, src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/util/LocalDateToWelshStringConverterTest.java
https://tools.hmcts.net/jira/browse/DFR-478
=> DFR-478 - Bulk DN batches get stuck in scheduler

charts/div-dgs/Chart.yaml
=> bump java chart

build.gradle
=> Bump springframework

dependency-check-suppressions.xml
Suppressing jackson-databind until 5-28
=> Suppressing Jackson-Databind

build.gradle
Bumping jackson databind to 2.13.3
Fixing CVE-2020-36518
=> Bumping jackson-databind

Jenkinsfile_nightly
=> fix nightly build

build.gradle
=> Bump snakeyaml

dependency-check-suppressions.xml
=> Supress Jackson databind

build.gradle, dependency-check-suppressions.xml
=> Fix dependency issues

build.gradle, charts/div-dgs/Chart.yaml
https://tools.hmcts.net/jira/browse/DFR-1808
=> Dfr 1808 chart update

build.gradle
Reduce CVE count in Divorce
https://tools.hmcts.net/jira/browse/DFR-1492
=> Dfr 1492 CVE updates

dependency-check-suppressions.xml
Reduce CVE count in Divorce
https://tools.hmcts.net/jira/browse/DFR-1492
Maintenance
=> Further CVE Suppression of Major updates

build.gradle
DFR-3783 Remove Jitpack dependency 
=> DFR-3783 Remove Jitpack dependency 

dependency-check-suppressions.xml
=> Suppress CVE-2025-48734
